### ISSUE TITLE
Just a heads up

### ISSUE THREAD

**Issue by brisingraerowing** [Robmaister/SharpFont.Dependencies#2]
I am currently building binaries for FreeType 2.6. I will issue a pull request when I am finished.

**Comment by Robmaister** [comment]
:+1:

If you're also planning on building the base version with no extra dependencies, make sure to apply the exact patch I included (see the README here: https://github.com/Robmaister/SharpFont.Dependencies/tree/master/freetype2)

**Comment by brisingraerowing** [comment]
Pull Request submitted. I have an identical patch file that I use already.

Sorry for taking so long, VS does not like to cooperate sometimes.
